name: Test code on push
on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  LaunchUnitTests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run unit tests
      run: cargo test --verbose
